const types = {
  LANDING_CHECK: 'LANDING_CHECK',
  EDIT_MODE: 'EDIT_MODE',
  LOGIN_DATA: 'LOGIN_DATA',
  LOGIN_DATA_IU_CAR: 'LOGIN_DATA_IU_CAR',
  LOGIN_DATA_LOCATION: 'LOGIN_DATA_LOCATION',
  LOGIN_DATA_ID: 'LOGIN_DATA_ID',
};

export default types;
